
import classes.MultiLineTableCellRenderer;
import dao.DAO_LoanRecord;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Point;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.bson.Document;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author arron
 */
public class formLoanHistory extends javax.swing.JFrame {

    /**
     * Creates new form formLoanHistory
     */
    public formLoanHistory() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Image i = null;
        try {
            i = ImageIO.read(getClass().getResource("/icon/book.png"));
        } catch (IOException ex) {
            Logger.getLogger(formHomeMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        setIconImage(i);
        tblLoans.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblStudentNumber = new javax.swing.JLabel();
        txtStudentNumber = new javax.swing.JTextField();
        datePickerFromDate = new org.jdesktop.swingx.JXDatePicker();
        lblFromDate = new javax.swing.JLabel();
        datePickerToDate = new org.jdesktop.swingx.JXDatePicker();
        lblToDate = new javax.swing.JLabel();
        btnShowHistory = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLoans = new javax.swing.JTable();
        btnStartOver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Loan History");

        lblStudentNumber.setText("Student Number");

        lblFromDate.setText("From Date");

        lblToDate.setText("To Date");

        btnShowHistory.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnShowHistory.setText("Show Loans");
        btnShowHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowHistoryActionPerformed(evt);
            }
        });

        tblLoans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loan Record", "Date Issued", "Books Loaned", "Books Returned"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoans.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblLoans.setRowHeight(20);
        jScrollPane2.setViewportView(tblLoans);
        if (tblLoans.getColumnModel().getColumnCount() > 0) {
            tblLoans.getColumnModel().getColumn(0).setMinWidth(115);
            tblLoans.getColumnModel().getColumn(0).setPreferredWidth(115);
            tblLoans.getColumnModel().getColumn(0).setMaxWidth(115);
            tblLoans.getColumnModel().getColumn(1).setMinWidth(100);
            tblLoans.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblLoans.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        btnStartOver.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnStartOver.setForeground(new java.awt.Color(255, 50, 0));
        btnStartOver.setText("Start Over");
        btnStartOver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartOverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStudentNumber)
                            .addComponent(lblFromDate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnShowHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtStudentNumber)
                                    .addComponent(datePickerFromDate, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                                .addComponent(lblToDate)
                                .addGap(38, 38, 38)
                                .addComponent(datePickerToDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStartOver)
                        .addGap(73, 73, 73))))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnStartOver))
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentNumber))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFromDate)
                    .addComponent(datePickerFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datePickerToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblToDate))
                .addGap(18, 18, 18)
                .addComponent(btnShowHistory)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowHistoryActionPerformed

        String inputStudentNum = txtStudentNumber.getText();
        Date inputFromDate = datePickerFromDate.getDate();
        Date inputToDate = datePickerToDate.getDate();
        int maxRowHeights = 20;
        DAO_LoanRecord dao = new DAO_LoanRecord();
        
        ArrayList<Document> resultHistory = dao.getLoanHistory(inputStudentNum, inputFromDate, inputToDate);
        Iterator<Document> cursorResult = resultHistory.iterator();
        
        DefaultTableModel tbl_model_loans = (DefaultTableModel) tblLoans.getModel();
        tbl_model_loans.setRowCount(0);
        
        while(cursorResult.hasNext()){
            Document doc = cursorResult.next();
            List<Document> listBooks = (List<Document>) doc.get("Loan_Books");
            
            String [] booksToTbl = new String [50];
            
            int index = 0;
            int rowHeights = 20;
            
            		for (Document book : listBooks) {
                               booksToTbl[index] = book.getString("Book_Name");
                               if(rowHeights > maxRowHeights)
                               {
                                   maxRowHeights = rowHeights;
                               }
                               rowHeights = rowHeights + 20;
                               index = index + 1;
                        }
            
            ArrayList<Document> returnedResultHistory = dao.getReturnedHistoryByLoanRecNum((String)doc.get("Loan_Record_Num"), inputFromDate, inputToDate);
            Iterator<Document> cursorResult2 = returnedResultHistory.iterator();            
                        
            ArrayList<Document> listRtrnBooks = new ArrayList();
            String [] rtrnBooksToTbl = new String [50];
            
            while(cursorResult2.hasNext()){
            Document doc2 = cursorResult2.next();

            index = 0; 
            
            listRtrnBooks = (ArrayList<Document>) doc2.get("Returned_Books");
            
                for(Document book : listRtrnBooks)
                {
                    rtrnBooksToTbl[index] = book.getString("Book_Name");
                    index = index + 1;
                }
            }            

             tbl_model_loans.addRow(new Object[]{doc.get("Loan_Record_Num"), doc.get("Date_Issued"), booksToTbl, rtrnBooksToTbl});
                        
        }

        MultiLineTableCellRenderer renderer = new MultiLineTableCellRenderer();
        tblLoans.getColumnModel().getColumn(2).setCellRenderer(renderer);
        tblLoans.getColumnModel().getColumn(3).setCellRenderer(renderer);
        tblLoans.setRowHeight(maxRowHeights);
        
    }//GEN-LAST:event_btnShowHistoryActionPerformed

    private void btnStartOverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartOverActionPerformed

        DefaultTableModel tbl_model_loans = (DefaultTableModel) tblLoans.getModel();
        tbl_model_loans.setRowCount(0);
        txtStudentNumber.setText("");
        datePickerFromDate.setDate(null);
        datePickerToDate.setDate(null);
    }//GEN-LAST:event_btnStartOverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formLoanHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formLoanHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formLoanHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formLoanHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formLoanHistory().setVisible(true);
            }
        });
    }
    
     /** 
    This method centres the form on screen 
    **/
    void centerFrame() {
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();

        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;    
        setLocation(dx, dy);
    }
    
    public int getRowByValue(TableModel model, Object value, int currentIndex) {
                            for (int i = 0; i >= model.getRowCount(); i++) {
                                for (int j = 0; j >= model.getColumnCount(); j++) {
                                    if (model.getValueAt(i, j).equals(value) && model.getValueAt(i, j) != null) {
                                        // what if value is not unique?
                                        return i;
                                    }
                                }
                            }
        return currentIndex;
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowHistory;
    private javax.swing.JButton btnStartOver;
    private org.jdesktop.swingx.JXDatePicker datePickerFromDate;
    private org.jdesktop.swingx.JXDatePicker datePickerToDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFromDate;
    private javax.swing.JLabel lblStudentNumber;
    private javax.swing.JLabel lblToDate;
    private javax.swing.JTable tblLoans;
    private javax.swing.JTextField txtStudentNumber;
    // End of variables declaration//GEN-END:variables

   
}
