
import classes.MultiLineTableCellRenderer;
import dao.DAO_DataWarehouse;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Point;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.bson.Document;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author arron
 */
public class formQuestion9 extends javax.swing.JFrame {

    /**
     * Creates new form formLoanHistory
     */
    public formQuestion9() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Image i = null;
        try {
            i = ImageIO.read(getClass().getResource("/icon/book.png"));
        } catch (IOException ex) {
            Logger.getLogger(formQuestion9.class.getName()).log(Level.SEVERE, null, ex);
        }
        setIconImage(i);
        tblAverageRetained.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblStudentNumber = new javax.swing.JLabel();
        btnShowLoans = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAverageRetained = new javax.swing.JTable();
        btnStartOver = new javax.swing.JButton();
        comboCampus = new javax.swing.JComboBox<>();
        comboDate = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Busiest Day of the Year");

        btnShowLoans.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnShowLoans.setText("Show Loans");
        btnShowLoans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowLoansActionPerformed(evt);
            }
        });

        tblAverageRetained.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Day of Year", "Loan Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAverageRetained.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblAverageRetained.setRowHeight(20);
        jScrollPane2.setViewportView(tblAverageRetained);
        if (tblAverageRetained.getColumnModel().getColumnCount() > 0) {
            tblAverageRetained.getColumnModel().getColumn(0).setResizable(false);
            tblAverageRetained.getColumnModel().getColumn(0).setPreferredWidth(400);
            tblAverageRetained.getColumnModel().getColumn(1).setResizable(false);
            tblAverageRetained.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        btnStartOver.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnStartOver.setForeground(new java.awt.Color(255, 50, 0));
        btnStartOver.setText("Start Over");
        btnStartOver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartOverActionPerformed(evt);
            }
        });

        comboCampus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Campuses", "Hogwarts", "Ninnymuggins", "Sunnyville" }));
        comboCampus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCampusActionPerformed(evt);
            }
        });

        comboDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2015", "2016", "2017", "2018", "2019", "2020" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblStudentNumber)
                        .addGap(18, 312, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(comboCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnShowLoans, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnStartOver)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnStartOver))
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStudentNumber)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowLoans)
                    .addComponent(comboCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowLoansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowLoansActionPerformed

        String comboYear = comboDate.getSelectedItem().toString();
        
        int year = Integer.parseInt(comboYear);
        
        String campus = comboCampus.getSelectedItem().toString();
        
        if(campus.equals("All Campuses")){
            campus = ".";
        }
        
        DAO_DataWarehouse dao = new DAO_DataWarehouse();
        
        ArrayList<Document> resultHistory = dao.getBusiestDayOfYear(comboYear, campus);
        Iterator<Document> cursorResult = resultHistory.iterator();
        
        DefaultTableModel tbl_model_days = (DefaultTableModel) tblAverageRetained.getModel();
        tbl_model_days.setRowCount(0);
        
        while(cursorResult.hasNext()){
            Document day = cursorResult.next();
            String date = day.get("Day_Key").toString().substring(0, 10);
            tbl_model_days.addRow(new Object[]{date, day.get("Loan_Amount")});
                        
        }
        
    }//GEN-LAST:event_btnShowLoansActionPerformed

    private void btnStartOverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartOverActionPerformed
   
        DefaultTableModel tbl_model_days = (DefaultTableModel) tblAverageRetained.getModel();
        tbl_model_days.setRowCount(0);

    }//GEN-LAST:event_btnStartOverActionPerformed

    private void comboCampusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCampusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCampusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formQuestion9().setVisible(true);
            }
        });
    }
    
     /** 
    This method centres the form on screen 
    **/
    void centerFrame() {
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();

        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;    
        setLocation(dx, dy);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowLoans;
    private javax.swing.JButton btnStartOver;
    private javax.swing.JComboBox<String> comboCampus;
    private javax.swing.JComboBox<String> comboDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblStudentNumber;
    private javax.swing.JTable tblAverageRetained;
    // End of variables declaration//GEN-END:variables

   
}
