
import dao.DAO_LoanRecord;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Point;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aaron Morris, s1408926
 * @version 1.0
 * 
 */
public class formFinePaidHistory extends javax.swing.JFrame {

    /**
     * Creates new form formFinePaidHistory
     */
    public formFinePaidHistory() {
        initComponents();
        //Set the default close operation, so that the application does not stop upon closing form
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Image i = null;
        try {
            i = ImageIO.read(getClass().getResource("/icon/book.png"));
        } catch (IOException ex) {
            Logger.getLogger(formHomeMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        setIconImage(i);
        tblFineHistory.setAutoCreateRowSorter(true);
                
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtStudentNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        datePickerDateFrom = new org.jdesktop.swingx.JXDatePicker();
        datePickerDateTo = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnShowFines = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFineHistory = new javax.swing.JTable();
        btnStartOver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTotalFine = new javax.swing.JTextPane();
        lblTotalFine = new javax.swing.JLabel();
        lblPoundSign = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Fine History");

        jLabel2.setText("Student Number");

        jLabel3.setText("Date From");

        jLabel4.setText("Date To");

        btnShowFines.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnShowFines.setText("Show Fines");
        btnShowFines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowFinesActionPerformed(evt);
            }
        });

        tblFineHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Loaned", "Amount Paid (£)", "Date Paid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFineHistory);
        if (tblFineHistory.getColumnModel().getColumnCount() > 0) {
            tblFineHistory.getColumnModel().getColumn(1).setMinWidth(100);
            tblFineHistory.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblFineHistory.getColumnModel().getColumn(1).setMaxWidth(100);
            tblFineHistory.getColumnModel().getColumn(2).setMinWidth(100);
            tblFineHistory.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblFineHistory.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        btnStartOver.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnStartOver.setForeground(new java.awt.Color(255, 50, 0));
        btnStartOver.setText("Start Over");
        btnStartOver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartOverActionPerformed(evt);
            }
        });

        txtTotalFine.setEditable(false);
        jScrollPane2.setViewportView(txtTotalFine);

        lblTotalFine.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotalFine.setText("Total Fines");

        lblPoundSign.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPoundSign.setText("£");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStartOver)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datePickerDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addComponent(jLabel4)
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnShowFines)
                            .addComponent(datePickerDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTotalFine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPoundSign)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnStartOver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datePickerDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(datePickerDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(btnShowFines)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalFine)
                            .addComponent(lblPoundSign)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowFinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowFinesActionPerformed
        String inputStudentNum = txtStudentNumber.getText();
        Date inputFromDate = datePickerDateFrom.getDate();
        Date inputToDate = datePickerDateTo.getDate();
        Double totalFine = 0.0;
        //The next two lines instantiate a decimal format object, and set the maximum allowed decimal points to 2 (on any formatted decimal number)
        DecimalFormat df = new DecimalFormat();
        df.setMaximumFractionDigits(2);
        
        //instantiate Data Access Object
        
        DAO_LoanRecord dao = new DAO_LoanRecord();
        
        //Retrieve a student's fine history, based on the parameters set from the user's input
        ArrayList<Document> fineHistory = dao.getFineHistory(inputStudentNum, inputFromDate, inputToDate);
        Iterator<Document> fineIterator = fineHistory.iterator();
        //Grab the tabel model as an Object
        DefaultTableModel tbl_model_fines = (DefaultTableModel) tblFineHistory.getModel();
        
        tbl_model_fines.setRowCount(0);
        txtTotalFine.setText("");
        
        //While the Mongo Cursor, associated with the Student's fine history, has more documents to iterate though; iterate through them
        while(fineIterator.hasNext()){
            Document doc = fineIterator.next();
            Double fineAmount = (Double) doc.get("Amount_Paid");
            totalFine = totalFine + fineAmount;
            
            if(doc != null)
            {
      
                    tbl_model_fines.addRow(new Object[]{doc.get("Book_Name"), df.format(doc.get("Amount_Paid")), doc.get("Date_Paid")});
       
            }
            txtTotalFine.setText(df.format(totalFine));
  
        }
   
    }//GEN-LAST:event_btnShowFinesActionPerformed

    private void btnStartOverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartOverActionPerformed
      
        DefaultTableModel tbl_model_fines = (DefaultTableModel) tblFineHistory.getModel();
        tbl_model_fines.setRowCount(0);
        txtTotalFine.setText("");
        txtStudentNumber.setText("");
        datePickerDateFrom.setDate(null);
        datePickerDateTo.setDate(null);
    }//GEN-LAST:event_btnStartOverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formFinePaidHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formFinePaidHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formFinePaidHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formFinePaidHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formFinePaidHistory().setVisible(true);
            }
        });
    }
    
    /** 
    This method centres the form on screen 
    **/
    void centerFrame() {
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();

        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;    
        setLocation(dx, dy);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowFines;
    private javax.swing.JButton btnStartOver;
    private org.jdesktop.swingx.JXDatePicker datePickerDateFrom;
    private org.jdesktop.swingx.JXDatePicker datePickerDateTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblPoundSign;
    private javax.swing.JLabel lblTotalFine;
    private javax.swing.JTable tblFineHistory;
    private javax.swing.JTextField txtStudentNumber;
    private javax.swing.JTextPane txtTotalFine;
    // End of variables declaration//GEN-END:variables

    
}
